### ISSUE TITLE
Add clouds

### ISSUE THREAD

**Issue by andrewmcwatters** [Planimeter/vertex-adventure#10]

**Comment by ltmp** [comment]
Just something to think about on this one, shadows for clouds could also work similarly to how the tree shadows already work.

**Comment by andrewmcwatters** [comment]
I didn't really think about the fact that shadow projection for clouds could be conveyed the same way it works for entities. That's a pretty solid observation and it would allow us to extend other shadow functionality to the clouds `regionlayer`. It would modify visibility based on night/day cycle.

To elaborate, I think I'd like to implement this as a custom `regionlayer` that has a `parallax` option. It could then be added by level designers in Tiled. I'm not sure yet, however.

**Comment by andrewmcwatters** [comment]
Closing this for now.
