### ISSUE TITLE
Add inventory

### ISSUE THREAD

**Issue by andrewmcwatters** [Planimeter/vertex-adventure#11]

**Comment by ltmp** [comment]
Just to briefly re-iterate over what we talked about on Skype:

* The inventory could possibly be an "extension" of the menu panel
* The inventory could also be docked to the top of the window in a 1x(item amount) format, but this really depends on how item management works in the gameplay
* In regards to the above, customization of location and the like could be useful? It's not like we need EVE Online windows, but having the ability to adjust is great for managing your playstyle.
* The inventory has sorting options ("by hand", amount, type, subtype, rarity, etc)
* The inventory has category options (Spells, Utility, etc)
* The inventory should be able to be opened via mouse but also through keybindings

Let me know if anything else comes to mind.

**Comment by andrewmcwatters** [comment]
:+1: Gonna implement this after work today. Not sure about the category options yet, but I think it's a given they'll eventually be there, or somewhere else readily accessible from the HUD.

**Comment by ltmp** [comment]
Yeah I really feel it's dependant on whatever comes along in the terms of
gameplay mechanics, if anything it should be approached in an open-ended way in
case we need to manipulate it later.
