### ISSUE TITLE
Request for Quests

### ISSUE THREAD

**Issue by andrewmcwatters** [Planimeter/vertex-adventure#3]
TODO

**Comment by ltmp** [comment]
Commenting to tag myself in this and to remind me to get back to writing.

**Comment by ltmp** [comment]
Whoops, thought you could have multiple assignee's. That's kind of stupid.

**Comment by andrewmcwatters** [comment]
There really should be.

**Comment by andrewmcwatters** [comment]
Restructuring request issues for the upcoming holidays.
