### ISSUE TITLE
Request for Game Notes

### ISSUE THREAD

**Issue by andrewmcwatters** [Planimeter/vertex-adventure#4]
TODO

**Comment by andrewmcwatters** [comment]
During the timeline of VA, the name "Nimrod" as an idiom didn't refer to _"a dimwitted or a stupid person."_ https://en.wikipedia.org/wiki/Nimrod#Idiom

**Comment by andrewmcwatters** [comment]
Disease would be interesting to implement.

**Comment by andrewmcwatters** [comment]
A paralysis spell called "ossificate" or something to that effect would be neat. I'm wondering if incantations should have a medieval latin sound to them?
https://en.wikipedia.org/wiki/Ossification

**Comment by andrewmcwatters** [comment]
Mentioning @ltmp and @ryan-kingstone just in case you guys have cool ideas you wanna see happen.

**Comment by andrewmcwatters** [comment]
*Genuflect* should be an option when right clicking on royalty or something like that. That would be a cool but probably pointless feature.

**Comment by ltmp** [comment]
Everytime I read the word Genuflect i think it's spelt Gnuflect so I associate it with something like "a response to reflect a non-free software believer" lmao.

**Comment by ltmp** [comment]
If you're using Windows 10 you should probably Gnuflect yourself!!!

**Comment by andrewmcwatters** [comment]
lmao

**Comment by ryan-kingstone** [comment]
Buffs/Drugs that has the possibility to cause addiction (think Fallout)

**Comment by andrewmcwatters** [comment]
:+1:

**Comment by andrewmcwatters** [comment]
Restructuring request issues for the upcoming holidays.
